# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c02d584b7ce8fbc111faaed5e0ce3993f086ffde95f0e464194271ca3ca2a97a8b3e3c4fccfbe70a20c92f57bc69c437fe4c35112fa9fc079a959cfbc33957f0

test:
  secret_key_base: 830fcd56b133b6eccaeffdd853baac25e4fbef544d61cb7efc7e93d5dc5043460cd3d264d5218419c0d3e82bd356550548c1e7512144e689015f17658a5af026

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
